FROM leafai/studio-go-runner-dev-base:0.0.4

MAINTAINER karlmutch@gmail.com

ENV LANG C.UTF-8

ENV GOPATH=/project
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH:/project/.local/bin

ENV LOGXI='*=INF'
ENV LOGXI_FORMAT='happy,maxcol=1024'

RUN mkdir -p /project/.local/bin && \
    wget -q -O /project/.local/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio && \
    chmod +x /project/.local/bin/minio

RUN \
    mkdir -p $GOPATH/bin && \
    (curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh) && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    git config --global url."https://".insteadOf git:// && \
    go get github.com/karlmutch/enumer && \
    go get github.com/karlmutch/petname && \
    go install github.com/karlmutch/petname/cmd/petname && \
    wget -q -O $GOPATH/bin/semver https://github.com/karlmutch/duat/releases/download/0.12.0/semver-linux-amd64 && \
    wget -q -O $GOPATH/bin/stencil https://github.com/karlmutch/duat/releases/download/0.12.0/stencil-linux-amd64 && \
    chmod +x $GOPATH/bin/semver && \
    chmod +x $GOPATH/bin/stencil

WORKDIR /project/src/github.com/leaf-ai/studio-go-runner

LABEL author="Karl Mutch"

# Done last to prevent lots of disruption when bumping versions
LABEL vendor="Open Source"
